# Generated by Django 5.0.1 on 2024-02-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ename",
            field=models.CharField(max_length=255),
        ),
    ]
